---

- name: install httpd package and start httpd service
  hosts: webservers
  become: yes
  gather_facts: true 
  vars: 
    package_name: httpd
    package_state: present
    service_name: httpd
    service_state: restarted
  tasks:

    - name: Installing httpd package
      package:
        name: "{{ package_name }}"
        state: "{{ package_state }}"

    - name: Starting up httpd service
      service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
        enabled: yes


