---

- name: install {{ package_name }} package and start {{ service_name }} service
  hosts: webservers
  become: yes
  gather_facts: true
  vars:
    package_name: tftp , vsftpd
    package_state: present
    service_name: vsftpd
    service_state: restarted
  tasks:

    - name: Installing {{ package_name }} package
      package:
        name: "{{ package_name }}"
        state: "{{ package_state }}"

    - name: Starting up {{ service_name }} service
      service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
        enabled: yes
